### Install Packages for the Project
install.packages("rvest")
install.packages("dplyr")
install.packages("tidyverse")
install.packages("stringr")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("shinythemes")
install.packages("DT")
install.packages("leaflet")
install.packages("knitr")
install.packages("htmltools")
install.packages("shinyWidgets")
install.packages("flextable")
install.packages("gridExtra")
install.packages("jpeg")
install.packages("janitor")
install.packages("kableExtra")
install.packages("tableHTML")
install.packages("fmsb")


### Include the library
library(rvest)
library(dplyr)
library(tidyverse)
library(stringr)
library(shiny)
library(shinydashboard)
library(shinythemes)
library(DT)
library(leaflet)
library(knitr)
library(htmltools)
library(flextable)
library(magrittr)
library(gridExtra)
library(jpeg)
library(janitor)
library(kableExtra)
library(tableHTML)
library(fmsb)

